FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

RUN install_packages \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-good \
    gstreamer1.0-tools \
    htop \
    jq \
    v4l-utils

WORKDIR /usr/src

COPY start.sh *.txt ./

CMD ["/bin/bash", "/usr/src/start.sh"]
