FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine

RUN install_packages ffmpeg v4l-utils omxplayer jq

WORKDIR /usr/src
COPY start.sh .
COPY 1080P50EDID.txt .

CMD while : ; do echo "${MESSAGE=Idling...}"; sleep ${INTERVAL=600}; done
# CMD ["/bin/bash", "/usr/src/start.sh"]